Profile: NgClaimInvoice
Parent: Invoice
Id: ng-claim-invoice
Title: "NG-Claim Invoice"
Description: "A profile for invoices generated by providers for reimbursement."

* status 1..1 MS
* subject 1..1 MS
* date 1..1 MS
* totalGross 0..1 MS
* totalNet 0..1
* participant 0..* MS
* lineItem 0..* MS
